import pandas as pd

# Old categories from topics.json
# CATEGORIES: pd.DataFrame = pd.DataFrame([
#     [1, "Restaurants, cafe, fast food", "restaurant"],
#     [2, "Chocolate, cookies, candy, ice cream", "chocolate"],
#     [3, "Chips, snacks, nuts, fruit, gum, cereal, yogurt, soups", "chips"],
#     [4, "Seasoning, condiments, ketchup", "seasoning"],
#     [5, "Pet food", "petfood"],
#     [6, "Alcohol", "alcohol"],
#     [7, "Coffee, tea", "coffee"],
#     [8, "Soda, juice, milk, energy drinks, water", "soda"],
#     [9, "Cars, automobiles (car sales, auto parts, car insurance, car repair, gas, motor oil, etc.)", "cars"],
#     [10, "Electronics (computers, laptops, tablets, cellphones, TVs, etc.)", "electronics"],
#     [11, "Phone, TV and internet service providers", "phone_tv_internet_providers"],
#     [12, "Financial services (banks, credit cards, investment firms, etc.)", "financial"],
#     [13, "Education (universities, colleges, kindergarten, online degrees, etc.)", "education"],
#     [14, "Security and safety services (anti-theft, safety courses, etc.)", "security"],
#     [15, "Software (internet radio, streaming, job search website, grammar correction, travel planning, etc.)",
#      "software"],
#     [16, "Other services (dating, tax, legal, loan, religious, printing, catering, etc.)", "other_service"],
#     [17, "Beauty products and cosmetics (deodorants, toothpaste, makeup, hair products, laser hair removal, etc.)",
#      "beauty"],
#     [18, "Healthcare and medications (hospitals, health insurance, allergy, cold remedy, home tests, vitamins)",
#      "healthcare"],
#     [19, "Clothing and accessories (jeans, shoes, eye glasses, handbags, watches, jewelry)", "clothing"],
#     [20, "Baby products (baby food, sippy cups, diapers, etc.)", "baby"],
#     [21, "Games and toys (including video and mobile games)", "game"],
#     [22, "Cleaning products (detergents, fabric softeners, soap, tissues, paper towels, etc.)", "cleaning"],
#     [23, "Home improvements and repairs (furniture, decoration, lawn care, plumbing, etc.)", "home_improvement"],
#     [24, "Home appliances (coffee makers, dishwashers, cookware, vacuum cleaners, heaters, music players, etc.)",
#      "home_appliance"],
#     [25, "Vacation and travel (airlines, cruises, theme parks, hotels, travel agents, etc.)", "travel"],
#     [26, "Media and arts (TV shows, movies, musicals, books, audio books, etc.)", "media"],
#     [27, "Sports equipment and activities", "sports"],
#     [28, "Shopping (department stores, drug stores, groceries, etc.)", "shopping"],
#     [29, "Gambling (lotteries, casinos, etc.)", "gambling"],
#     [30, "Environment, nature, pollution, wildlife", "environment"],
#     [31, "Animal rights, animal abuse", "animal_right"],
#     [32, "Human rights", "human_right"],
#     [33, "Safety, safe driving, fire safety", "safety"],
#     [34, "Smoking, alcohol abuse", "smoking_alcohol_abuse"],
#     [35, "Domestic violence", "domestic_violence"],
#     [36, "Self esteem, bullying, cyber bullying", "self_esteem"],
#     [37, "Political candidates (support or opposition)", "political"],
#     [38, "Charities", "charities"],
#     [39, "Unclear", "unclear"]], columns=['label', 'description', 'text'])


CATEGORIES: pd.DataFrame = pd.DataFrame([
    [1, 'Grocery', "Chips, snacks, nuts, fruit, gum, cereal, yogurt, soups, Chocolate, cookies, candy, ice cream, chocolate, Seasoning, condiments, ketchup, seasoning"],
    [2, 'Pet Supplies', "Pet food, petfood"],
    [3, 'Alcohol', "Alcohol, alcohol"],
    [4, 'Soda', "Soda, juice, milk, energy drinks, water soda Coffee, tea, coffee"],
    [5, 'Coffee Tea', "Coffee, tea"],
    [6, 'Automotive', "Cars, automobiles (car sales, auto parts, car insurance, car repair, gas, motor oil, etc.)"],
    [7, 'Electronics', "Electronics (computers, laptops, tablets, cellphones, TVs, etc.), electronics"],
    [8, 'Media', "Phone, TV and internet service providers, phone_tv_internet_providers"],
    [9, 'Financial', "Financial services (banks, credit cards, investment firms, etc.)"],
    [10, 'Education', "Education (universities, colleges, kindergarten, online degrees, etc.)"],
    [11, 'Security', "Security and safety services (anti-theft, safety courses, etc.)"],
    [12, 'Software', "Software (internet radio, streaming, job search website, grammar correction, travel planning, etc.)"],
    [13, 'Other Services',  "Other services (dating, tax, legal, loan, religious, printing, catering, etc.)"],
    [14, 'Beauty', "Beauty products and cosmetics (deodorants, toothpaste, makeup, hair products, laser hair removal, etc.)"],
    [15, 'Health', "Healthcare and medications (hospitals, health insurance, allergy, cold remedy, home tests, vitamins)"],
    [16, 'Job', 'Job Offerts'],
    [17, 'Clothing', "Clothing and accessories (jeans, shoes, eye glasses, handbags, watches, jewelry)"],
    [18, 'Baby', "Baby products (baby food, sippy cups, diapers, etc.)"],
    [19, 'Games and Toys', "Games and toys (including video and mobile games)"],
    [20, 'Cleaning products', "Cleaning products (detergents, fabric softeners, soap, tissues, paper towels, etc.)"],
    [21, 'Home', "Home improvements and repairs (furniture, decoration, lawn care, plumbing, etc.) Home appliances (coffee makers, dishwashers, cookware, vacuum cleaners, heaters, music players, etc.)"],
    [22, 'Travel', "Vacation and travel (airlines, cruises, theme parks, hotels, travel agents, etc.)"],
    [23, 'Arts', "Media and arts (TV shows, movies, musicals, books, audio books, etc.)"],
    [24, 'Sports', "Sports equipment and activities"],
    [25, 'Shopping stores', "Shopping (department stores, drug stores, groceries, etc.) Restaurants, cafe, fast food"],
    [26, 'Gambling', "Gambling (lotteries, casinos, etc.)"],
    [27, 'Social issue', "Domestic violence, Self esteem, bullying, cyber bullying, Political candidates (support or opposition), charities, Human rights, Safety, safe driving, fire safety, Smoking, alcohol abuse, Environment, nature, pollution, wildlife , environment, Animal rights, animal abuse"],
    [28, 'Social sites', 'Social Sites, Twitter, Facebook, Insta, Dating Sites'],
    [29, 'Tools and Hardware', "Stationery & Office Supplies, Tools & Hardware"]
     ], columns=['label', 'text', 'description'])

NUM_CATEGORIES = CATEGORIES.shape[0]

if __name__ == '__main__':
    CATEGORIES.to_csv('label_categories.csv', index=False)
